# Generated by Django 5.2 on 2025-08-28 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(upload_to='shared/banners/')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'bannerlar',
            },
        ),
    ]
