# Generated by Django 5.2 on 2025-09-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
