# Generated by Django 5.2 on 2025-09-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'kutilmoqda'), ('PROCESSING', 'qayta ishlash'), ('SHIPPED', "jo'natilgan"), ('DELIVERED', 'yetkazib berildi'), ('CANCELLED', 'bekor qilingan')], default='kutilmoqda', max_length=20),
        ),
    ]
