# Generated by Django 5.2 on 2025-09-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_address_order_comment_order_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
