# Generated by Django 5.2 on 2025-09-04 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=50)),
                ('tg_id', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'yetkazib beruvchi',
                'verbose_name_plural': 'yetkazib beruvchilar',
            },
        ),
    ]
