# Generated by Django 5.2 on 2025-09-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'naqd'), ('ACCOUNT_NUMBER', 'hisob raqam')], max_length=20, null=True),
        ),
    ]
