# Generated by Django 5.2 on 2025-09-02 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Birlik',
                'verbose_name_plural': 'Birliklar',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.unity'),
        ),
    ]
