# Generated by Django 5.2 on 2025-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_unity_product_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='unity',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='unity',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
