# Generated by Django 5.2 on 2025-09-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_code_product_irticle_product_tg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='irticle',
            new_name='article',
        ),
    ]
