# Generated by Django 5.2 on 2025-09-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_irticle_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_left',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
